"""empty message

Revision ID: 64891e751ad0
Revises: 65355eed151e
Create Date: 2025-01-23 14:44:53.364914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64891e751ad0'
down_revision = '65355eed151e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.drop_column('density_level')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('level')
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index('level', ['level'], unique=True)

    with op.batch_alter_table('detection_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('density_level', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
