"""이상행동 삭제

Revision ID: 65355eed151e
Revises: 99403f6e65b1
Create Date: 2025-01-22 12:23:26.746328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65355eed151e'
down_revision = '99403f6e65b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abnormal_behavior_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abnormal_behavior_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('detection_time', mysql.DATETIME(), nullable=True),
    sa.Column('cctv_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('fall_status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cctv_id'], ['cctvs.cctv_id'], name='abnormal_behavior_logs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf32',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
